### PR TITLE
Rename userscript.js to Userscript.user.js

### PR DESCRIPTION
**Pull request by AKASGaming**
Userscript managers will detect these automatically when viewing the file raw

### CODE REVIEW

**Comment by CanadaHonk** [comment]
If doing this, rename it to something like `arrpc.user.js` instead of a generic name?

**Review by CanadaHonk — CHANGES_REQUESTED** [review]
If doing this, rename it to something like `arrpc.user.js` instead of a generic name?

**Comment by AKASGaming** [comment]
Agreed! 👍

**Review by CanadaHonk — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
