### PR TITLE
Make Executables with "pkg"

### PR DESCRIPTION
**Pull request by AKASGaming**
I pretty much converted this so that you can use `pkg` to generate executables with the intention of having arRPC opening on startup with Windows in the startup folder.

The only problems it has right now is that it only detects games after you open the game the launch the program, and I think it's sending "just started" to Discord each time it scans

### CODE REVIEW

**Comment by AKASGaming** [comment]
I think I've narrowed it down to the processes list not updating once it's called

**Comment by AKASGaming** [comment]
I just got this to work, maybe consider making this a different branch? or at least including the binaries in a release?

**Comment by lexisother** [comment]
I am pretty sure no is no.

**Comment by CanadaHonk** [comment]
There is 0 use case to have a binary. You can use batch files for that kind of shortcut. I have no interest in binaries as it just makes things more unneededly untrustworthy and dangerous. Converting from ESM to CJS will never happen as it is only a step backwards.

**Comment by CanadaHonk** [comment]
Trying to be kind, please understand the nature of open source is not to contribute something that fits your needs but rather to improve upstream as a whole.

**Comment by AKASGaming** [comment]
How could possibly you know if people may or may not want this too. I certainly found it pretty frustrating that I had to put in a command every time I wanted to open the program, and yes a batch script is a solution but why not just have something like this incorporated already? It's not like this would be the only way to run the program, it's simply option

**Comment by CanadaHonk** [comment]
This only makes code worse and distribution less safe, it makes nothing better. If *you* want to use it, you can, that's why you have forks.

**Comment by Craftzman7** [comment]
Why did you covert away from ESM?

**Pull request closed without merging**
