### PR TITLE
Fix for userscript that broke a few days ago

### PR DESCRIPTION
**Pull request by ariankordi**
I'm sure some people noticed, but a recent Discord update broke a lot of things, arRPC included. It stopped working, seemingly because most of the heuristics to hook functions didn't work anymore.
I tried to fix arRPC.user.js (didn't retroactively change it across other scripts that had the same code) and it does work for me now, by improving some heuristics
More significantly, you may notice that lookupApp is not using Discord's function anymore, rather a fetch (found here: https://github.com/cool-dev-code/DiscordBotClient/blob/c8d3c9ae510fb6d30434a890f2e64fb72af3a68d/arRPC/examples/bridge_mod.js#L36)
and I am HOPING that won't cause any issues to happen.

Feel free to make this a whole lot better or steal some parts, I honestly won't expect this to be merged as-is (especially with that ugly tabbing you may see, lol.........)
I wasn't able to find any project that uses arRPC's userscript who has fixed it independently, so there may be better fixes out there.

### CODE REVIEW

**Comment by CanadaHonk** [comment]
Thanks, but we shouldn't use `fetch` directly.

**Review by CanadaHonk — CHANGES_REQUESTED** [review]
We shouldn't use `fetch`, instead the same modules as before.

**Comment by ariankordi** [comment]
So I redid that function, it wasn't picking up until I made it run on page load which I added to the userscript and hope isn't TOO ugly. Also removed the superfluous regex which probably caused more issues than it solved.
I finally applied these fixes in every script it appeared (making sure to change `msg` to `data` for the Electron part though that is UNTESTED!)
Let me know if there's anything else you woud prefer, the userscript is working perfectly fine for me.
image

**Review by CanadaHonk — APPROVED** [review]
LGTM thanks!

**Pull request merged**
